### ISSUE TITLE
README.cn.md doesn't follow naming convention

### ISSUE THREAD

**Issue by paddy-hack** [RichardLitt/standard-readme#111]
The spec states that projects supporting I18N should use BCP 47 for language tags.

I don't know Chinese but I do know that `cn` is not a BCP 47 *language* tag :smile:  
I do know Japanese so am able to recognize some of the characters.

Looking at README.cn.md it appears to be Simplified Chinese which normally uses `zh_CN`.  I suggest renaming the file.

You might use `zh` but that is almost guaranteed to upset people in Taiwan who use Traditional Chinese, `zh_TW`.  This looks different enough that I can *usually* tell the difference given enough text (even though I cannot really read it).  Actually, there are more variants (some would even be served better by the three letter language tags) for regions with large groups of Chinese speakers, such as `zh_HK` and `zh_SG`.

**Comment by wooorm** [comment]
Interesting! Not sure how `cn` slipped in.

My 2cts is go with `zh`. We do not know which regions the author(s) came from, but we do know that it is Chinese (hence `zh`), in the simplified script (trusting your judgement, giving `zh-Hans`). We can then hopefully stay away from regions. However, Unicode CLDR suggests that `zh-Hans` is more information that often needed: because `Hans` is the most used script associated with the macrolanguage `zh`, `zh` implies `Hans`. (They also suggest using `pt` for Portuguese as spoken in Brazil, `en` for English as spoken in the USA, `es` for Spanish in South America).

**Comment by paddy-hack** [comment]
We don't know about the initial translator but there are a pile of fixes by @bugstop who claims to be from Shenzhen, Guangdong.

Either way, almost definitely mainland China, so I'd go with `zh_CN`.  
My 2 yen :wink:

**Comment by notfresh** [comment]
ok, i will check it later~

**Comment by notfresh** [comment]
OK, i will fix it soon

**Comment by notfresh** [comment]
so now the commits in my PR have updated the correct filename as you guys suggested~

**Comment by RichardLitt** [comment]
I'm not seeing an open PR. Am I missing something?

**Comment by bugstop** [comment]
Well, `cn` is a strange convention, but I think just use `zh` hurts readability because we Chinese might miss it since it's not widely used.  
Actually, from my point of view, `zh-Hans` and `zh-Hant` better describe the difference between simplified Chinese and traditional Chinese, because we use *nearly* the same grammar and vocabulary. The writings might look totally different (because we use different sets of characters), but we can read each other's content.  
However, for readability, I suggest keep `cn` in, and `zh-CN` is a compromise.

**Comment by wooorm** [comment]
@RichardLitt The PR was https://github.com/RichardLitt/standard-readme/pull/115 I believe. I think this can be closed.

To recap my opinion: I feel “zh” or “zh-Hans” would be preferred (per Unicode) over “zh-CN”, although they’re all valid per BCP-47. And `cn` is nonstandard per both.

**Comment by RichardLitt** [comment]
Thanks, all. I think what we have works well, if I read this right.
