### ISSUE TITLE
Add reasoning to each section

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/standard-readme#13]
I wonder if it would be good to add, directly in the spec, reasoning for each section. This might add more extraneous content to the spec, but it might make it clearer why certain choices have been made. Thoughts?

**Comment by diasdavid** [comment]
IETF RFCs add a section at the beginning saying that X Y and Z should be interpreted as described by some other spec, so that there isn't anything ambiguous. I like what it offers but dislike the implementation cause it is too verbose.

An idea:

Each time there is a word that has a meaning on the standard-readme space, you could add a special char (like ⊛) and add a link to this repo, on the section that describes that word meaning in the context.

**Comment by RichardLitt** [comment]
Hmm. I was not clear enough. 

I mean, should there be justifications for decisions made in sections - not in the case of confusing terminology, but in the case of "Why did you put the Contribute section here?", or, "Why README and not readme?" This could also be discussed in the issues, and perhaps that is a better place to do it.

**Comment by RichardLitt** [comment]
I am going to not do this. I think that any questions can happen in the issues, and trying to _a priori_ predict them is bound to be suboptimal.
