### ISSUE TITLE
Note: Moved Repo

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/standard-readme#2]
I have moved this repo to my own name from the [IPFS](//github.com/ipfs/ipfs) org, because I think it will be more general than just for IPFS. My plan is to work on this and build it into something that can be used for other projects. 

This will be of course based partially on [zcei's standard-readme](https://github.com/zcei/standard-readme/issues/1), as I finally have the time to take on the issue originally posed by @maxogden over at feross/standard in [this issue](https://github.com/feross/standard/issues/141).

**Comment by zcei** [comment]
Haha what a coincidence, I also finally got some time to work on `standard-readme` again.

The roadmap in #1 seems a bit too IPFS specific, it hasn't been edited since the move, am I right?

Nevertheless: there was immediately feedback on my attempt to revive the project and @wooorm (the author of `remark`) is still on board to help.
So we have *the* expert for the tool right away on the project.

I love to hear your findings since then, especially for the yet-not-decided topics! (like API section)
Maybe we can bundle the power again and eventually build a tool together, instead of parallel. :)

**Comment by RichardLitt** [comment]
It has been edited a bit - I am going to make it a bit more general. But it will be a standard, and it won't be configurable - I am OK with that. 

Yeah, @wooorm is awesome, but he's not going to do the work for us. :) The issue is that mdast doesn't have a .config option, at the moment, AFAIK. Instead of dealing with rules, I am just making very specific modules that deal with what I want and leaving it at that. It stops a ton of bikeshedding. If you want to help me make those, jump in. As it is, I'm expecting to ask @wooorm only for bug fixing, but I think we should be able to do this without too much effort. 

I'm trying to build for IPFS because it seems easier to go with this specific use case than to build a generic tool. I do hope to add this to my [generator-nms](//github.com/RichardLitt/generator-nms) tool, too.

**Comment by RichardLitt** [comment]
@zcei I edited it a lot, today! I've now got a full spec, and I'm working on a generator and a linter at the moment. Would love your feedback. 

Going to close this, for now.
