### ISSUE TITLE
Quoting the short description / tagline

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/standard-readme#22]
@feross:

> Never been a fan of quoting the tagline. It de-emphasizes something that ought to be emphasized. 

@LinusU

> I too have been rubbed the wrong way with the idea that the tagline or short description should be inside a block-quote. It doesn't feel right, maybe this is an issue that should be raised upstream?

I'm not sure that it is de-emphasized. To me, it clearly separates the text from all other text. On GitHub, this looks like color and bolding - a strong statement. In text, there is the `>`, which points it out. 

Can we think of any sensible way to judge this objectively and not make a call based on aesthetic opinion of GitHub's coloring?

**Comment by davidak** [comment]
I also don't like the aesthetic how GitHub (and many others) renders it.

>Can we think of any sensible way to judge this objectively and not make a call based on aesthetic opinion of GitHub's coloring?

Probably not. How people perceive style and layout is subjective and probably influenced by culture.

A UX-expert can probably help here.

I think **making the sentence bold** would have the desired impact and is right in a semantic manner.

What i found in the wild:

- Title and tagline as banner https://github.com/vhesener/Closures#readme
- Bold text, sometimes as H4 hading (what's semantically wrong) https://github.com/thelounge/thelounge#readme
- As part of Title (i think it's too heavy) https://github.com/sr6033/lterm#readme
- Just text separated with newline from rest of description https://github.com/webpro/release-it#readme

Most Readmes don't have a tagline at all. It might not be needed on GitHub because the project description is shown at the top, but the readme is also used in other places, for example when checked out locally! So i think having it is useful.

**Comment by RichardLitt** [comment]
What do you mean by "a semantic manner"? How is bold different, semantically, than using a blockquote?

**Comment by davidak** [comment]
@RichardLitt bold formatting means it's important. a blockquote is a citation of someone.

**Comment by RichardLitt** [comment]
I can see what you mean, but I think that's an oversimplification.

One of the things I like about the citation is that it sets the description apart. What I don't want is for it to blend into the long description - the paragraph afterwards. Using bold is encouraging that, as bold sentences can be part of a wider paragraph easily. A blockquote can't. As well, the quote should match whatever is in the package manifests, as well as the GitHub description. One could argue that you are quoting someone else in the description, there.

**Comment by RichardLitt** [comment]
Tradeoffs. :/

**Comment by LinusU** [comment]
> [...] based on aesthetic opinion of GitHub's coloring?

It's not just GitHub, it's very common to style blockquotes with gray and indent it.

I personally don't like it because we are abusing something that was made for something else and using it just to achieve some specific style. That is, we are telling GitHub that this is a quote, when it isn't...

> As well, the quote should match whatever is in the package manifests [...]

Npm automatically pulls the description out by getting the first paragraph from the readme, does it still do this correctly when quoting that line? 🤔 

> One could argue that you are quoting someone else in the description, there.

Can't say that I agree with this. If I write something down in two places I can't really say that one is a quote of the other one? By that logic either the GitHub description or the package.json description should have quotation marks around them, since one of them is a quote of the other...

Just my 2¢ ☺️

**Comment by RichardLitt** [comment]
> Npm automatically pulls the description out by getting the first paragraph from the readme, does it still do this correctly when quoting that line? 🤔

This is a good question. I tend to copy this quote directly into the `description` field in the `package.json`, but that's not covered in this spec. I don't know the answer to this. 

Yeah, I see your points. I'm just not sure I agree that it's worth changing at the moment. But I may be wrong.

**Comment by wooorm** [comment]
I’m against the blockquote:
- On GH, it de-emphasises the important parts
- Semantically (as in, markdown/HTML), it isn’t really a quote now is it?
- Readmes get cluttered, especially the start, with many different things: badges, images, marketing-speak, the way to declutter and focus on the important part is, in my opinion, not to add more different styles, but rather to just have a paragraph or so of normal text!

Anyway, this discussion isn’t really going anywhere so I’m also in favour of tabling it!

**Comment by RichardLitt** [comment]
I think I am illogically holding on to what I did four years ago because I'm too lazy to admit that it may have not have been the best choice at the time.

Let's remove the block quote.
