### ISSUE TITLE
Feature: Automatically run example code in a REPL

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/standard-readme#28]
There should be a tool that does this on top of the standard-readme spec.

**Comment by martinheidegger** [comment]
There is [`run-markdown`](https://github.com/carlwoodward/run-markdown) That does something similar. In its current state it is not well usable because you can't prepare an environment for the test. _(specify code that you don't need to be visible within the markdown file)_. But I think think in general it is good practise - I don't know how often I published broken docs ...

**Comment by RichardLitt** [comment]
This would have to be a suggestion, as some code can't easily be run in a REPL. We could suggest run-markdown. Or others?

**Comment by martinheidegger** [comment]
If there is a linter, it should include a way to pass the code snippets to an executor: i.e. if there is a 

```javascript
console.log('Hello')
```

and you run the readme against `standard-readme --exec="npm run test-doc"`

and it will execute the above snippet like:

`echo "console.log('Hello')" | npm run test-doc -- 1`

**Comment by RichardLitt** [comment]
Agreed about this is something that ought to be worked into the linter. Going to link it to #5 and leave this open for now.

**Comment by wooorm** [comment]
Is this something standard-readme can dictate? 🤔 I’d leave this up to platforms that render readmes!

**Comment by RichardLitt** [comment]
Agreed.
